[pytest]
testpaths = tests
python_files = test_*.py
addopts = --ignore=tests/legacy
filterwarnings =
	ignore:.*addParseAction.*deprecated.*:DeprecationWarning:ezdxf.queryparser
	ignore:.*oneOf.*deprecated.*:DeprecationWarning:ezdxf.queryparser
	ignore:.*setResultsName.*deprecated.*:DeprecationWarning:ezdxf.queryparser
	ignore:.*infixNotation.*deprecated.*:DeprecationWarning:ezdxf.queryparser