"""Compatibility wrapper for extracted sheet-metal analysis helpers."""

from manufacturing_pipeline.analysis.sheetmetal import complete_analysis as _sheetmetal_complete_analysis
from manufacturing_pipeline.analysis.sheetmetal import geometry_analysis as _sheetmetal_geometry_analysis
from manufacturing_pipeline.analysis.sheetmetal import standards as _sheetmetal_standards

HAS_OCP = _sheetmetal_geometry_analysis.HAS_OCP

STANDARD_THICKNESSES = _sheetmetal_standards.STANDARD_THICKNESSES
STANDARD_BEND_ANGLES = _sheetmetal_standards.STANDARD_BEND_ANGLES
BendTool = _sheetmetal_standards.BendTool
STANDARD_V_DIES = _sheetmetal_standards.STANDARD_V_DIES
K_FACTORS = _sheetmetal_standards.K_FACTORS
MATERIAL_BEND_PROPERTIES = _sheetmetal_standards.MATERIAL_BEND_PROPERTIES
BendSequenceOptimizer = _sheetmetal_standards.BendSequenceOptimizer
calculate_bend_allowance = _sheetmetal_standards.calculate_bend_allowance
calculate_bend_deduction = _sheetmetal_standards.calculate_bend_deduction
calculate_flat_length = _sheetmetal_standards.calculate_flat_length
get_minimum_bend_radius = _sheetmetal_standards.get_minimum_bend_radius
recommend_v_opening = _sheetmetal_standards.recommend_v_opening
calculate_bend_force = _sheetmetal_standards.calculate_bend_force
calculate_complete_flat_pattern = _sheetmetal_standards.calculate_complete_flat_pattern

DetectedBend = _sheetmetal_geometry_analysis.DetectedBend
analyze_sheet_metal_geometry = _sheetmetal_geometry_analysis.analyze_sheet_metal_geometry

analyze_sheetmetal_complete = _sheetmetal_complete_analysis.analyze_sheetmetal_complete
_recommend_machine = _sheetmetal_complete_analysis._recommend_machine
